import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className="text-3xl font-bold underline dark text-primary">
                Welcome hello ! to <a href="https://nextjs.org">Next.js!</a>
            </h1>
        </>
    );
};

export default Home;
